apiVersion: v1
kind: ServiceAccount
metadata:
  name: tesla-collector-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tesla-collector-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tesla-collector-rolebinding
subjects:
  - kind: ServiceAccount
    name: tesla-collector-sa
roleRef:
  kind: Role
  name: tesla-collector-role
  apiGroup: rbac.authorization.k8s.io
