[CmdletBinding()]
param(
    [string]$VaultAddr = $env:VAULT_ADDR,
    [string]$VaultToken = $env:VAULT_TOKEN,
    [string]$SecretsMount = 'kv',
    [string]$RuntimeSecret = 'zeroclaw',
    [string]$AutomationSecret = 'automation',
    [string]$SecureStackEnvPath,
    [string[]]$TerraformArgs,
    [string]$TerraformWorkingDir,
    [string]$AppRolePath = 'approle',
    [string]$RoleIdFile,
    [string]$SecretIdFile,
    [switch]$UseAppRole,
    [string]$AutomationVaultToken = $env:VAULT_AUTOMATION_TOKEN,
    [string]$AutomationRoleIdFile,
    [string]$AutomationSecretIdFile,
    [switch]$UseAutomationAppRole,
    [string]$AutomationAppRolePath,
    [string]$TelegramConfigPath,
    [switch]$SkipTelegramConfig
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Resolve-FullPath {
    param([string]$Path, [string]$Base)
    if (-not $Path) {
        throw 'Path parameter is required.'
    }
    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }
    return [System.IO.Path]::GetFullPath((Join-Path -Path $Base -ChildPath $Path))
}

function Get-FileContentOrNull {
    param([string]$Path)
    if (-not $Path) { return $null }
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "File not found: $Path"
    }
    return (Get-Content -LiteralPath $Path -ErrorAction Stop | Select-Object -First 1).Trim()
}

function Get-VaultTokenInternal {
    param(
        [string]$VaultAddr,
        [string]$VaultToken,
        [switch]$UseAppRole,
        [string]$RoleIdFile,
        [string]$SecretIdFile,
        [string]$AppRolePath
    )
    if ($VaultToken) {
        return $VaultToken
    }
    $shouldUseAppRole = $UseAppRole -or $RoleIdFile -or $SecretIdFile
    if ($shouldUseAppRole) {
        $roleId = Get-FileContentOrNull -Path $RoleIdFile
        $secretId = Get-FileContentOrNull -Path $SecretIdFile
        $loginBody = @{ role_id = $roleId; secret_id = $secretId } | ConvertTo-Json -Compress
        $uri = "{0}/v1/auth/{1}/login" -f $VaultAddr.TrimEnd('/'), $AppRolePath.Trim('/')
        $response = Invoke-RestMethod -Uri $uri -Method Post -Body $loginBody -ContentType 'application/json'
        return $response.auth.client_token
    }
    $defaultTokenPath = Join-Path -Path $HOME -ChildPath '.vault-token'
    if (Test-Path -LiteralPath $defaultTokenPath) {
        return (Get-Content -LiteralPath $defaultTokenPath | Select-Object -First 1).Trim()
    }
    throw 'Vault token not provided. Set VAULT_TOKEN, pass -UseAppRole, or log in via `vault login`.'
}

function ConvertTo-Hashtable {
    param([object]$InputObject)
    if ($null -eq $InputObject) {
        return @{}
    }
    if ($InputObject -is [System.Collections.IDictionary]) {
        return $InputObject
    }
    $hash = @{}
    foreach ($property in $InputObject.PSObject.Properties) {
        $hash[$property.Name] = $property.Value
    }
    return $hash
}

function ConvertTo-TelegramAllowedUsersToml {
    param([object]$Value)
    if ($null -eq $Value) {
        return '[]'
    }

    if ($Value -is [System.Collections.IEnumerable] -and -not ($Value -is [string])) {
        $items = @()
        foreach ($entry in $Value) {
            $text = ("$entry").Trim()
            if ($text) {
                $items += '"' + $text + '"'
            }
        }
        if ($items.Count -eq 0) {
            return '[]'
        }
        return '[' + ($items -join ', ') + ']'
    }

    $textValue = ("$Value").Trim()
    if (-not $textValue) {
        return '[]'
    }

    $tokens = $textValue -split '[,;]' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
    $tokens = @($tokens)
    if ($tokens.Count -eq 0) {
        return '[]'
    }

    $quoted = $tokens | ForEach-Object { '"' + $_ + '"' }
    return '[' + ($quoted -join ', ') + ']'
}

function Get-TelegramConfigTemplate {
    @"
# Generated by automation/scripts/sync-vault-secrets.ps1. Do not edit manually.
workspace_dir = "/zeroclaw-data/workspace"
config_path = "/zeroclaw-data/.zeroclaw/config.toml"
api_key = ""
api_url = "http://host.docker.internal:11435"
default_provider = "ollama"
default_model = "llama3.2"
default_temperature = 0.3

[gateway]
port = 3000
host = "gateway"
allow_public_bind = false

[agent]
compact_context = true
max_tool_iterations = 8
max_history_messages = 60
parallel_tools = true

[observability]
backend = "prometheus"

[channels_config]
cli = false

[channels_config.telegram]
bot_token = "__BOT_TOKEN__"
allowed_users = __ALLOWED_USERS__
stream_mode = "off"
draft_update_interval_ms = 1000
mention_only = false
interrupt_on_new_message = false

[http_request]
enabled = true
allowed_domains = ["*"]
max_response_size = 2097152
timeout_secs = 60

[web_search]
enabled = true
provider = "duckduckgo"
max_results = 5
timeout_secs = 15
"@
}

function Update-TelegramConfig {
    param(
        [hashtable]$RuntimeData,
        [string]$ConfigPath
    )

    if (-not $RuntimeData) {
        return
    }

    if (-not $RuntimeData.ContainsKey('TELEGRAM_BOT_TOKEN')) {
        Write-Warning 'Runtime secret missing TELEGRAM_BOT_TOKEN; skipped Telegram config render.'
        return
    }

    $botToken = ("$($RuntimeData['TELEGRAM_BOT_TOKEN'])").Trim()
    if (-not $botToken) {
        Write-Warning 'TELEGRAM_BOT_TOKEN is empty; skipped Telegram config render.'
        return
    }

    $allowedUsersToml = ConvertTo-TelegramAllowedUsersToml -Value $RuntimeData['TELEGRAM_ALLOWED_USERS']
    $template = Get-TelegramConfigTemplate
    $content = $template.Replace('__BOT_TOKEN__', $botToken).Replace('__ALLOWED_USERS__', $allowedUsersToml)

    $configDir = Split-Path -Parent $ConfigPath
    if (-not (Test-Path -LiteralPath $configDir)) {
        New-Item -ItemType Directory -Path $configDir -Force | Out-Null
    }

    Set-Content -Path $ConfigPath -Value $content -Encoding UTF8
    Write-Host "Rendered Telegram config: $ConfigPath"
}

function Get-VaultSecretData {
    param([string]$VaultAddr, [string]$Token, [string]$Mount, [string]$Name)
    $uri = "{0}/v1/{1}/data/{2}" -f $VaultAddr.TrimEnd('/'), $Mount.Trim('/'), $Name.Trim('/')
    $headers = @{ 'X-Vault-Token' = $Token }
    $response = Invoke-RestMethod -Uri $uri -Method Get -Headers $headers -ErrorAction Stop
    return ConvertTo-Hashtable -InputObject $response.data.data
}

# Derive default paths if not provided
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $SecureStackEnvPath) {
    $SecureStackEnvPath = Join-Path -Path $scriptRoot -ChildPath '..\..\zeroclaw\deploy\secure-stack\.env'
}
if (-not $TerraformWorkingDir) {
    $TerraformWorkingDir = Join-Path -Path $scriptRoot -ChildPath '..\terraform'
}
$SecureStackEnvPath = Resolve-FullPath -Path $SecureStackEnvPath -Base $scriptRoot
$TerraformWorkingDir = Resolve-FullPath -Path $TerraformWorkingDir -Base $scriptRoot

if (-not $VaultAddr) {
    throw 'Vault address not provided. Set VAULT_ADDR or pass -VaultAddr.'
}

if (-not $AutomationAppRolePath) {
    $AutomationAppRolePath = $AppRolePath
}
if (-not $TelegramConfigPath) {
    $TelegramConfigPath = Join-Path -Path $scriptRoot -ChildPath '..\..\zeroclaw\deploy\secure-stack\configs\telegram\config.toml'
}

$TelegramConfigPath = Resolve-FullPath -Path $TelegramConfigPath -Base $scriptRoot

$token = Get-VaultTokenInternal -VaultAddr $VaultAddr -VaultToken $VaultToken -UseAppRole:$UseAppRole -RoleIdFile $RoleIdFile -SecretIdFile $SecretIdFile -AppRolePath $AppRolePath
$automationToken = $token
if ($AutomationVaultToken -or $UseAutomationAppRole -or $AutomationRoleIdFile -or $AutomationSecretIdFile) {
    $automationToken = Get-VaultTokenInternal -VaultAddr $VaultAddr -VaultToken $AutomationVaultToken -UseAppRole:$UseAutomationAppRole -RoleIdFile $AutomationRoleIdFile -SecretIdFile $AutomationSecretIdFile -AppRolePath $AutomationAppRolePath
}

$runtimeData = $null
try {
    $runtimeData = Get-VaultSecretData -VaultAddr $VaultAddr -Token $token -Mount $SecretsMount -Name $RuntimeSecret
} catch {
    Write-Warning "Runtime secret ${SecretsMount}/${RuntimeSecret} not found: $($_.Exception.Message)"
}

if ($runtimeData) {
    $envLines = @()
    foreach ($key in ($runtimeData.Keys | Sort-Object)) {
        $value = $runtimeData[$key]
        if ($null -ne $value) {
            $envLines += "$key=$value"
        }
    }
    $secureStackDir = Split-Path -Parent $SecureStackEnvPath
    if (-not (Test-Path -LiteralPath $secureStackDir)) {
        New-Item -ItemType Directory -Path $secureStackDir -Force | Out-Null
    }
    if ($envLines.Count -gt 0) {
        Set-Content -Path $SecureStackEnvPath -Value ($envLines -join [Environment]::NewLine) -Encoding UTF8
        Write-Host "Wrote secure stack env file: $SecureStackEnvPath"
    } else {
        Write-Warning 'Runtime secret returned no key/value pairs; skipped .env generation.'
    }

    if (-not $SkipTelegramConfig) {
        Update-TelegramConfig -RuntimeData $runtimeData -ConfigPath $TelegramConfigPath
    }
}

$automationData = $null
try {
    $automationData = Get-VaultSecretData -VaultAddr $VaultAddr -Token $automationToken -Mount $SecretsMount -Name $AutomationSecret
} catch {
    Write-Warning "Automation secret ${SecretsMount}/${AutomationSecret} not found: $($_.Exception.Message)"
}

if ($automationData -and $automationData.ContainsKey('tailscale_auth_key')) {
    $env:TF_VAR_tailscale_auth_key = $automationData['tailscale_auth_key']
    Write-Host 'TF_VAR_tailscale_auth_key exported for this PowerShell session.'
}

if ($TerraformArgs -and $TerraformArgs.Length -gt 0) {
    if (-not (Test-Path -LiteralPath $TerraformWorkingDir)) {
        throw "Terraform directory not found: $TerraformWorkingDir"
    }
    Push-Location -Path $TerraformWorkingDir
    try {
        & terraform @TerraformArgs
    } finally {
        Pop-Location
    }
}
